### ISSUE TITLE
Add Keybase for Pocket Keypairs

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-js-LEGACY#133]
Create a Keybase for client keys with the following features:

- Store multiple keypairs identified by address.
- Sign payloads with stored keypairs (using ed25519).
- Unlocks specific keys for passphrase free payload signing.
- CRUD operations on the keypairs.
- Verify proofs (using ed25519).

**Comment by nymd** [comment]
Spec says "Unlock specific keys for certain amounts of time"

I don't see any time-based unlocking in the deliverable -- should the time part of the spec be ignored?
