### ISSUE TITLE
RC-0.2.0 Compatibility

### ISSUE THREAD

**Issue by nymd** [pokt-network/pocket-js-LEGACY#231]
Full changelog: https://github.com/pokt-network/pocket-core/blob/staging/doc/changelog.md

**Comment by nymd** [comment]
https://github.com/pokt-network/pocket-core/issues/691
- Changes some RPC responses from camelCase to snake_case

**Comment by andrewnguyen22** [comment]
Good idea, also - Changed RPC and from `node-proof` to `node-receipt`

**Comment by nymd** [comment]
Full changelog: https://github.com/pokt-network/pocket-core/blob/staging/doc/changelog.md

**Comment by andrewnguyen22** [comment]
https://github.com/pokt-network/pocket-js/issues/238#issuecomment-597666952
