### ISSUE TITLE
Local consensus

### ISSUE THREAD

**Issue by nymd** [pokt-network/pocket-js-LEGACY#239]
Pocket-JS should offer an option for how many nodes must be in consensus in order to accept the response.

Currently one node is selected at random and the response is accepted as correct. The data consumer should be able to select how many nodes are required for response consensus when they instantiate the Configuration object for the PocketInstance.

If there is no consensus on the returned responses, a challenge transaction should be initiated.
- see: https://github.com/orgs/pokt-network/projects/43

____________

There are some concerns to work out based on how many nodes are selected for consensus:

- if an even number of nodes are required and the nodes are equally split on their responses, both responses should have challenge requests initiated.

- if an odd number of nodes are required and there is only one node out of the group that has a different response, only initiate the challenge on that node

____________

There should also be a selection in the configuration on whether the client will accept a response or reject it based on having a full consensus. Something like:

- flag acceptDisputedResponses: boolean, defaults to false
- Does the client accept a response when not all of the nodes are in consensus?  If set to true, a supermajority of nodes being in agreement will still accept result in accepting the response even if 1 or more nodes is not in agreement.

____________

Error handling and response should be robust so that downstream clients (like our Pocket Web3 lib) will be able to handle disputed responses.

**Comment by andrewnguyen22** [comment]
@nymd 

> if an even number of nodes are required and the nodes are equally split on their responses, both responses should have challenge requests initiated.

Should always be an odd number I think ^^

> if an odd number of nodes are required and there is only one node out of the group that has a different response, only initiate the challenge on that node

You can send the challenge to all nodes in the session too, (may want to make this configurable)

**NOTE**: node you are challenging would likely reject the challenge
> flag acceptDisputedResponses: boolean, defaults to false
Does the client accept a response when not all of the nodes are in consensus? If set to true, a supermajority of nodes being in agreement will still accept result in accepting the response even if 1 or more nodes is not in agreement

This is cool

**Comment by nymd** [comment]
I'm thinking restricting it to odd-only is probably the most straightforward though the frugal data consumer in me wants to use 2 to save on bandwidth and provide just one level of redundancy.
