### ISSUE TITLE
rc-0.3.0 Compatibility

### ISSUE THREAD

**Issue by nymd** [pokt-network/pocket-js-LEGACY#266]
https://github.com/pokt-network/pocket-core/blob/staging/doc/changelog.md

**Comment by pabelnl** [comment]
We are impacted by the following list based on pocket-core changelog:

- [x] Changed Proof field from relayResponse to proof
- [x] Added headers back to payload (affects request hash!)
- [x] New Dispatch Formula See Spec
- [x] Relay Response now has the entire proof when sent back to the client
- [x] Changed Struct used to generate RequestHash to remove empty proof object
- [x] Add pagination to Application Queries for RPC & CLI
- [x] Add pagination to Nodes Queries for RPC & CLI

**Comment by pabelnl** [comment]
Pocket-Core 0.3.0 changelog is missing two new rpc queries:

- [x] query/blocktxs
- [x] query/accounttxs

**Comment by pabelnl** [comment]
Update from pocket-core

> So now when we query apps and validators we actually use an opts object which will allow for greater filtering. However, this changes the query/apps and query/validators endpoints of the rpc
https://github.com/pokt-network/pocket-core/pull/808

**Comment by pabelnl** [comment]
Completion of rc-0.3.0 blocked by two issues:
https://github.com/pokt-network/pocket-core/issues/820
https://github.com/pokt-network/pocket-core/issues/819
