### ISSUE TITLE
Package module separation

### ISSUE THREAD

**Issue by pabelnl** [pokt-network/pocket-js-LEGACY#366]
Separate each module into separate packages, maintain a root package that contains all the sub-packages.

**Comment by Evalir** [comment]
Hey! Just wanted to comment on this, as I'm already seeing commits on another branch implementing this.

I'd *heavily* recommend using [Lerna](https://github.com/lerna/lerna) to set up the monorepo correctly—splitting the repo into multiple sub-packages without any way of cross-linking or managing dependencies on all sub-folders can become a hassle, and _is_ very painful during development. This is the standard way of doing this in the industry and we should not decide to do it differently IMHO. As a bonus, this also lets us publish packages together or independently in an interactive way using their CLI.
