### ISSUE TITLE
Query Nodes Should Not Fill in the Defaults

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-js-LEGACY#386]
**Describe the bug**
https://github.com/pokt-network/pocket-js/blob/55cad80c335d0f84652f501415ae2e0ca488e664/src/rpc/namespaces/query.ts#L258

Pocket Network RPC requires no staking status, jailed status etc. So the expected behavior is for PocketJS to have no defaults for these params and let them be blank or empty

Also the per_page default should match Pocket Network default at 10K not 60

**Comment by jorgecuesta** [comment]
The documentation of the endpoint say thay if sent nothing you will get all the validators
https://github.com/pokt-network/pocket-core/blob/staging/doc/rpc-spec.yaml#L752
